### ISSUE TITLE
3/28 Meeting Agenda

### ISSUE THREAD

**Issue by NukeManDan** [Colorado-Community-Resources/CORE-Website#10]
Please comment here to add items! :grin: 
@cryptoquick @proofoftom @astv99 @magician11 @oovg

**Comment by proofoftom** [comment]
For myself: setting up a Discourse this week, figure out who has ownership in the most fair way possible. Where will this live (hosting and domain wise) - am happy to provide hosting, and perhaps chat.coloradoblockchain.com?

**Comment by NukeManDan** [comment]
Cool @proofoftom ! I vote that we all have reduced/restricted privileges on this... but also not sure why we need a forum for the project yet? Discord is a good place to host us IMO for now (join here: https://discord.gg/pP8UEdF)

Mostly I want to make and *integration* to a forum in the community node. 

Also any integration with `coloradoblockchain.com` is not possible and not planned yet.

**Comment by NukeManDan** [comment]
Recording:
https://www.youtube.com/watch?v=A4RjNr4R_h0
https://www.youtube.com/watch?v=mkl30MjZ6HI
